name: dgis_map_kit_example
description: Demonstrates how to use the dgis_map_kit plugin.
publish_to: 'none'

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  dgis_map_kit:
    path: ../

  cupertino_icons: ^1.0.2

dependency_overrides:
  dgis_map_platform_interface:
    path: ../dgis_map_platform_interface

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/
