name: dgis_map_kit
description: 2Gis Flutter plugin, that allows you to integrate 2Gis SDK for your applicatioon.
repository: https://github.com/jyahann/dgis_map_kit.git
version: 0.0.6

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  dgis_map_platform_interface: ^0.0.2
  location: ^5.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

dependency_overrides:
  dgis_map_platform_interface:
    path: dgis_map_platform_interface

flutter:
  plugin:
    platforms:
      android:
        package: jyahann.dgis_map_kit
        pluginClass: DgisMapKitPlugin
      ios:
        pluginClass: DgisMapKitPlugin
